
name: list_tile
description: A simple custom Text widget package
version: 1.0.0
homepage: https://github.com/luckyYunicorn/list_tile
repository: https://github.com/luckyYunicorn/list_tile
documentation: https://github.com/luckyYunicorn/list_tile#readme
environment:
  sdk: '>=2.20.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
dev_dependencies:
  flutter_test:
    sdk: flutter
 